package com.abc.us.accounting.commons.domain.type

enum class ResultCode(val code: String) {
    SUCCEEDED("SUCCEEDED"),
    FAILED("FAILED"),

    DOCUMENT_NOT_FOUND("DOCUMENT_NOT_FOUND"),
    SEQUENCE_GENERATION("SEQUENCE_GENERATION"),


    DOCUMENT_STATUS_TRANSITION("DOCUMENT_STATUS_TRANSITION"),
    DOCUMENT_ITEM_STATUS_TRANSITION("DOCUMENT_ITEM_STATUS_TRANSITION"),
    APPROVAL_STATUS_TRANSITION("APPROVAL_STATUS_TRANSITION"),
    DOCUMENT_VALIDATION_ERROR("DOCUMENT_VALIDATION_ERROR"),
    DOCUMENT_REQUEST_TYPE_ERROR("DOCUMENT_REQUEST_TYPE_ERROR"),
    DOCUMENT_SAVE_EXCEPTION("DOCUMENT_SAVE_EXCEPTION"),

    ALREADY_FISCAL_PERIOD_CLOSED("ALREADY_FISCAL_PERIOD_CLOSED"),
    CLOSING_STATUS_TRANSITION("CLOSING_STATUS_TRANSITION"),
    PREVIOUS_PERIOD_NOT_CLOSED("PREVIOUS_PERIOD_NOT_CLOSED"),

    DATABASE_ERROR("E0"),
    EXTERNAL_SERVICE_ERROR("E002")
}
