package com.abc.us.accounting.collects.domain.type

enum class OrderItemStatusEnum(val value: String) {

    ORDER_RECEIVED("ORDER_RECEIVED"),
    ORDER_COMPLETED("ORDER_COMPLETED"),
    BOOKING_SCHEDULED("BOOKING_SCHEDULED"),
    BOOKING_CONFIRMED("BOOKING_CONFIRMED"),
    ORDER_ON_HOLD("ORDER_ON_HOLD"),
    WORK_IN_PROGRESS("WORK_IN_PROGRESS"),
    CONTRACT_CONFIRMED("CONTRACT_CONFIRMED"),
    INSTALL_COMPLETED("INSTALL_COMPLETED"),
    ORDER_CONFIRMED("ORDER_CONFIRMED"),
    CANCELLATION_RECEIVED("CANCELLATION_RECEIVED"),
    CANCELLATION_PROCESSING("CANCELLATION_PROCESSING"),
    CANCELLATION_REQUESTED("CANCELLATION_REQUESTED"),
    CANCELLATION_COMPLETED("CANCELLATION_COMPLETED"),
    RETURN_RECEIVED("RETURN_RECEIVED"),
    RETURN_PROCESSING("RETURN_PROCESSING"),
    RETURN_ON_HOLD("RETURN_ON_HOLD"),
    RETURN_COMPLETED("RETURN_COMPLETED"),
    REFUND_RECEIVED("REFUND_RECEIVED"),
    REFUND_PROCESSING("REFUND_PROCESSING"),
    REFUND_ON_HOLD("REFUND_ON_HOLD"),
    DISMANTLING_STARTED("DISMANTLING_STARTED"),
    MATERIAL_RETURNED("MATERIAL_RETURNED"),
    REFUND_COMPLETED("REFUND_COMPLETED"),
    SUSPENDED("SUSPENDED"),
    PRODUCT_PREPARING("PRODUCT_PREPARING"),
    DELIVERY_IN_PROGRESS("DELIVERY_IN_PROGRESS"),
    DELIVERY_COMPLETED("DELIVERY_COMPLETED"),
    NONE("NONE")
}

