package com.abc.us.accounting.collects.domain.type

//enum class ServiceFlowStatusEnum(val value: kotlin.String) {
//
//    SERVICE_CREATED("SERVICE_CREATED"),
//    SHIPPING_SCHEDULED("SHIPPING_SCHEDULED"),
//    BOOKING_SCHEDULED("BOOKING_SCHEDULED"),
//    BOOKING_CONFIRMED("BOOKING_CONFIRMED"),
//    SERVICE_SCHEDULED("SERVICE_SCHEDULED"),
//    SERVICE_STARTED("SERVICE_STARTED"),
//    SERVICE_COMPLETED("SERVICE_COMPLETED"),
//    SERVICE_CANCELED("SERVICE_CANCELED"),
//    SHIPPING_CANCELED("SHIPPING_CANCELED"),
//    BOOKING_CANCELED("BOOKING_CANCELED"),
//    SERVICE_ON_HOLD("SERVICE_ON_HOLD"),
//    NONE("NONE"),
//}

