package com.abc.us.accounting.logistics.domain.type

enum class MovementType(val code: String, val description: String) {
    //BEGINNING_INVENTORY("BEGINNING_INVENTORY", "기초재고"),

    ENDING_INVENTORY("BEGINNING_INVENTORY", "기말 재고"),

    //INBOUND_PURCHASE("INBOUND_PURCHASE", "구매입고"),
    //INBOUND_RETURN("INBOUND_PURCHASE", "반환 입고"),

    //INBOUND_INSTALLATION_RETURN("INBOUND_PURCHASE", "신설치 반환 입고"),
    //INBOUND_INSTALLATION_PURCHASE_RETURN("INBOUND_PURCHASE", "반환 입고(일시불)"),

    //SALES_RENTAL("SALES_RENTAL", "렌탈 판매"),

    //SALES_LEASE("SALES_LEASE", "리스 판매"),

    //END("END", "끝")

    INBOUND_PURCHASE_ORDER("INBOUND_PURCHASE_ORDER", "구매 주문 입고"),
    INBOUND_CUSTOMER_RETURN("INBOUND_CUSTOMER_RETURN", "고객 반품 입고"),
    INBOUND_BORROWED_RETURN("INBOUND_BORROWED_RETURN", "대여 반환 입고"),
    INBOUND_INVENTORY_ADJUSTMENT("INBOUND_INVENTORY_ADJUSTMENT", "재고 조정 입고"),
    INBOUND_CYCLE_COUNT_ADJUSTMENT("INBOUND_CYCLE_COUNT_ADJUSTMENT", "실사 차이에 의한 입고"),
    INBOUND_TRANSFER_FROM_OTHER_WAREHOUSE("INBOUND_TRANSFER_FROM_OTHER_WAREHOUSE", "다른 창고에서의 이동 입고"),
    INBOUND_UNPLANNED("INBOUND_UNPLANNED", "기타 입고"),

    OUTBOUND_SALES_ORDER("OUTBOUND_SALES_ORDER", "판매 주문 출고"),
    OUTBOUND_RETURN_TO_VENDOR("OUTBOUND_RETURN_TO_VENDOR", "공급업체로의 반품"),
    OUTBOUND_TRANSFER_TO_OTHER_WAREHOUSE("OUTBOUND_TRANSFER_TO_OTHER_WAREHOUSE", "다른 창고로의 이동 출고"),
    OUTBOUND_SCRAP_MATERIAL("OUTBOUND_SCRAP_MATERIAL", "폐기 출고"),
    OUTBOUND_SAMPLE_PROVISION("OUTBOUND_SAMPLE_PROVISION", "샘플 제공 출고"),
    OUTBOUND_CONSUMABLE_USAGE("OUTBOUND_CONSUMABLE_USAGE", "소모품 사용 출고"),
    OUTBOUND_UNPLANNED("OUTBOUND_UNPLANNED", "기타 출고"),

    IN_TRANSIT("IN_TRANSIT", "운송중")

}
