package com.abc.us.accounting.documents.domain.type

import jakarta.persistence.AttributeConverter
import jakarta.persistence.Converter

/**
 * QBO Account SubType
 * 참조링크: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account
 * @param value: String
 * @param displayName: String, QBO UI에서 표시되는 이름
 * @param qboAccountType: QboAccountType
 * @return QboAccountSubType
 * @see QBOAccountType
 */
enum class QBOAccountSubType(val value: String, val displayName:String, val qboAccountType: QBOAccountType) {
//    INCOME_TAX_PAYABLE("IncomeTaxPayable", "Income Tax Payable", QboAccountType.OTHER_CURRENT_LIABILITY),
//    INTANGIBLE_ASSETS_OTHER("IntangibleAssetsOther","Intangible Assets",  QboAccountType.FIXED_ASSET),
    ACCOUNTS_PAYABLE("AccountsPayable", "Accounts Payable (A/P)", QBOAccountType.ACCOUNTS_PAYABLE),
    ACCOUNTS_RECEIVABLE("AccountsReceivable","Accounts Receivable (A/R)", QBOAccountType.ACCOUNTS_RECEIVABLE),
    ACCUMULATED_ADJUSTMENT("AccumulatedAdjustment", "Accumulated Adjustment", QBOAccountType.EQUITY),
    ACCUMULATED_AMORTIZATION("AccumulatedAmortization", "Accumulated Amortization", QBOAccountType.FIXED_ASSET),
    ACCUMULATED_AMORTIZATION_OF_OTHER_ASSETS("AccumulatedAmortizationOfOtherAssets", "Accumulated Amortization of Other Assets", QBOAccountType.OTHER_ASSET),
    ACCUMULATED_DEPLETION("AccumulatedDepletion", "Accumulated Depletion", QBOAccountType.FIXED_ASSET),
    ACCUMULATED_DEPRECIATION("AccumulatedDepreciation", "Accumulated Depreciation", QBOAccountType.FIXED_ASSET),
    ADVERTISING_PROMOTIONAL("AdvertisingPromotional", "Advertising/Promotional", QBOAccountType.EXPENSE),
    ALLOWANCE_FOR_BAD_DEBTS("AllowanceForBadDebts", "Allowance for Bad Debts", QBOAccountType.OTHER_CURRENT_ASSET),
    AMORTIZATION("Amortization", "Amortization", QBOAccountType.OTHER_EXPENSE),
    AUTO("Auto", "Auto", QBOAccountType.EXPENSE),
    BAD_DEBTS("BadDebts", "Bad Debts", QBOAccountType.EXPENSE),
    BANK_CHARGES("BankCharges", "Bank Charges", QBOAccountType.EXPENSE),
    BUILDINGS("Buildings", "Buildings", QBOAccountType.FIXED_ASSET),
    CASH_ON_HAND("CashOnHand", "Cash on hand", QBOAccountType.BANK),
    CHARITABLE_CONTRIBUTIONS("CharitableContributions", "Charitable Contributions", QBOAccountType.EXPENSE),
    CHECKING("Checking", "Checking", QBOAccountType.BANK),
    COMMON_STOCK("CommonStock", "Common Stock", QBOAccountType.EQUITY),
    COST_OF_LABOR("CostOfLabor", "Cost of Labor", QBOAccountType.EXPENSE),
    COST_OF_LABOR_COS("CostOfLaborCos", "Cost of labor - COS", QBOAccountType.COST_OF_GOODS_SOLD),
    CREDIT_CARD("CreditCard", "Credit Card", QBOAccountType.CREDIT_CARD),
    DEPLETABLE_ASSETS("DepletableAssets", "Depletable Assets", QBOAccountType.FIXED_ASSET),
    DEPRECIATION("Depreciation", "Depreciation", QBOAccountType.OTHER_EXPENSE),
    DEVELOPMENT_COSTS("DevelopmentCosts", "Development Costs", QBOAccountType.OTHER_CURRENT_ASSET),
//    DIRECT_DEPOSIT_PAYABLE("DirectDepositPayable", "", QboAccountType.OTHER_CURRENT_LIABILITY),
    DISCOUNTS_REFUNDS_GIVEN("DiscountsRefundsGiven", "Discounts/Refunds Given", QBOAccountType.INCOME),
    DIVIDEND_INCOME("DividendIncome", "Divided Income", QBOAccountType.OTHER_INCOME),
    DUES_SUBSCRIPTIONS("DuesSubscriptions", "Dues & subscriptions", QBOAccountType.EXPENSE),
    EMPLOYEE_CASH_ADVANCES("EmployeeCashAdvances", "Employee Cash Advances", QBOAccountType.OTHER_CURRENT_ASSET),
    ENTERTAINMENT("Entertainment", "Entertainment", QBOAccountType.EXPENSE),
    ENTERTAINMENT_MEALS("EntertainmentMeals", "Entertainment Meals", QBOAccountType.EXPENSE),
    EQUIPMENT_RENTAL("EquipmentRental", "Equipment Rental", QBOAccountType.EXPENSE),
    EQUIPMENT_RENTAL_COS("EquipmentRentalCos", "Equipment Rental - COS", QBOAccountType.COST_OF_GOODS_SOLD),
    ESTIMATED_TAXES("EstimatedTaxes", "Estimated Taxes", QBOAccountType.EQUITY),
    EXCHANGE_GAIN_OR_LOSS("ExchangeGainOrLoss", "Exchange Gain or Loss", QBOAccountType.OTHER_EXPENSE),
    FEDERAL_INCOME_TAX_PAYABLE("FederalIncomeTaxPayable", "Federal Income Tax Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    FINANCE_COSTS("FinanceCosts",  "Finance costs", QBOAccountType.EXPENSE),
    FIXED_ASSET_COMPUTERS("FixedAssetComputers", "Fixed Asset Computers", QBOAccountType.FIXED_ASSET),
    FIXED_ASSET_COPIERS("FixedAssetCopiers", "Fixed Asset Copiers", QBOAccountType.FIXED_ASSET),
    FIXED_ASSET_FURNITURE("FixedAssetFurniture", "Fixed Asset Furniture", QBOAccountType.FIXED_ASSET),
    FIXED_ASSET_PHONE("FixedAssetPhone", "Fixed Asset Phone", QBOAccountType.FIXED_ASSET),
    FIXED_ASSET_PHOTO_VIDEO("FixedAssetPhotoVideo", "Fixed Asset Photo Video", QBOAccountType.FIXED_ASSET),
    FIXED_ASSET_SOFTWARE("FixedAssetSoftware", "Fixed Asset Software", QBOAccountType.FIXED_ASSET),
    FIXED_ASSET_OTHER_TOOLS_EQUIPMENT("FixedAssetOtherToolsEquipment", "Fixed Asset Other Tools Equipment", QBOAccountType.FIXED_ASSET),
    FURNITURE_AND_FIXTURES("FurnitureAndFixtures", "Furniture & Fixtures", QBOAccountType.FIXED_ASSET),
//    GLOBAL_TAX_EXPENSE("GlobalTaxExpense", "", QboAccountType.EXPENSE),
//    GLOBAL_TAX_PAYABLE("GlobalTaxPayable", "", QboAccountType.OTHER_CURRENT_LIABILITY),
//    GLOBAL_TAX_SUSPENSE("GlobalTaxSuspense","", QboAccountType.OTHER_CURRENT_LIABILITY),
    GAS_AND_FUEL("GasAndFuel", "Gas And Fuel", QBOAccountType.OTHER_EXPENSE),
    GOODWILL("Goodwill", "Goodwill", QBOAccountType.OTHER_ASSET),
    GRATUITY("Gratuity", "Undistributed Tips", QBOAccountType.OTHER_CURRENT_LIABILITY), // 확인필요
    DEFERRED_REVENUE("DeferredRevenue", "Deferred Revenue", QBOAccountType.OTHER_CURRENT_LIABILITY),
    HEALTHCARE("Healthcare", "Healthcare", QBOAccountType.EQUITY),
    HEALTH_SAVINGS_ACCOUNT_CONTRIBUTIONS("HealthSavingsAccountContributions", "Health Savings Account Contributions", QBOAccountType.EQUITY),
    HOME_OFFICE("HomeOffice", "Home Office", QBOAccountType.OTHER_EXPENSE),
    HOMEOWNER_RENTAL_INSURANCE("HomeownerRentalInsurance", "Homeowner Rental Insurance", QBOAccountType.OTHER_EXPENSE),
    INSURANCE("Insurance",  "Insurance", QBOAccountType.EXPENSE),
    INSURANCE_PAYABLE("InsurancePayable", "Insurance Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    INTANGIBLE_ASSETS("IntangibleAssets", "Intangible Assets", QBOAccountType.FIXED_ASSET),
    INTEREST_EARNED("InterestEarned", "Interest Earned", QBOAccountType.OTHER_INCOME),
    INTEREST_PAID("InterestPaid", "Interest Paid", QBOAccountType.EXPENSE),
    INVENTORY("Inventory", "Inventory", QBOAccountType.OTHER_CURRENT_ASSET),
    INVESTMENT_MORTGAGE_REAL_ESTATE_LOANS("Investment_MortgageRealEstateLoans", "Investment - Mortgage/Real Estate Loans", QBOAccountType.OTHER_ASSET),
    INVESTMENT_OTHER("Investment_Other", "Investments - Other", QBOAccountType.OTHER_CURRENT_ASSET),
    INVESTMENT_TAX_EXEMPT_SECURITIES("Investment_TaxExemptSecurities", "Investment - Tax-Exempt Securities", QBOAccountType.OTHER_CURRENT_ASSET),
    INVESTMENT_US_GOVERNMENT_OBLIGATIONS("Investment_USGovernmentObligations", "Investment - U.S. Government Obligations", QBOAccountType.OTHER_CURRENT_ASSET),
    LAND("Land", "Land", QBOAccountType.FIXED_ASSET),
    LEASE_BUYOUT("LeaseBuyout", "Lease Buyout", QBOAccountType.OTHER_ASSET),
    LEASEHOLD_IMPROVEMENTS("LeaseholdImprovements", "Leasehold Improvements", QBOAccountType.FIXED_ASSET),
    LEGAL_PROFESSIONAL_FEES("LegalProfessionalFees", "Legal & Professional Fees", QBOAccountType.EXPENSE),
    LICENSES("Licenses", "Licenses", QBOAccountType.OTHER_ASSET),
    LINE_OF_CREDIT("LineOfCredit", "Line of Credit", QBOAccountType.OTHER_CURRENT_ASSET),
    LOAN_PAYABLE("LoanPayable", "Loan Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    LOANS_TO_OFFICERS("LoansToOfficers", "Loans to Officers", QBOAccountType.OTHER_CURRENT_ASSET),
    LOANS_TO_OTHERS("LoansToOthers", "Loans to Others", QBOAccountType.OTHER_CURRENT_ASSET),
    LOANS_TO_STOCKHOLDERS("LoansToStockholders", "Loans to Stockholders", QBOAccountType.OTHER_CURRENT_ASSET),
    MACHINERY_AND_EQUIPMENT("MachineryAndEquipment", "Machinery & Equipment", QBOAccountType.OTHER_CURRENT_ASSET),
    MONEY_MARKET("MoneyMarket", "Money Market", QBOAccountType.BANK),
    MORTGAGE_INTEREST_HOME_OFFICE("MortgageInterestHomeOffice", "Mortgage Interest Home Office", QBOAccountType.OTHER_EXPENSE),
    NON_PROFIT_INCOME("NonProfitIncome", "Non-Profit Income", QBOAccountType.INCOME),
    NOTES_PAYABLE("NotesPayable", "Notes Payable", QBOAccountType.LONG_TERM_LIABILITY),
    OFFICE_GENERAL_ADMINISTRATIVE_EXPENSES("OfficeGeneralAdministrativeExpenses", "Office/General Administrative Expenses", QBOAccountType.EXPENSE),
    OPENING_BALANCE_EQUITY("OpeningBalanceEquity", "Opening Balance Equity", QBOAccountType.EQUITY),
    ORGANIZATIONAL_COSTS("OrganizationalCosts", "Organizational Costs", QBOAccountType.OTHER_ASSET),
    OTHER_BUSINESS_EXPENSES("OtherBusinessExpenses", "Other Business Expenses", QBOAccountType.EXPENSE),
    OTHER_COSTS_OF_SERVICE_COS("OtherCostsOfServiceCos", "Other Costs of Services - COS", QBOAccountType.COST_OF_GOODS_SOLD),
    OTHER_CURRENT_ASSETS("OtherCurrentAssets", "Other Current Assets", QBOAccountType.OTHER_CURRENT_ASSET),
    OTHER_CURRENT_LIABILITIES("OtherCurrentLiabilities", "Other Current Liabilities", QBOAccountType.OTHER_CURRENT_LIABILITY),
    OTHER_FIXED_ASSETS("OtherFixedAssets", "Other fixed assets", QBOAccountType.FIXED_ASSET),
//    OTHER_HOME_OFFICE_EXPENSES("OtherHomeOfficeExpenses", "", QboAccountType.OTHER_EXPENSE),
    OTHER_INVESTMENT_INCOME("OtherInvestmentIncome", "Other Investment Income", QBOAccountType.INCOME),
    OTHER_LONG_TERM_ASSETS("OtherLongTermAssets", "Other Long-term Assets", QBOAccountType.OTHER_ASSET),
    OTHER_LONG_TERM_LIABILITIES("OtherLongTermLiabilities", "Other Long Term Liabilities", QBOAccountType.LONG_TERM_LIABILITY),
    OTHER_MISCELLANEOUS_EXPENSE("OtherMiscellaneousExpense", "Other Miscellaneous Expense", QBOAccountType.OTHER_EXPENSE),
    OTHER_MISCELLANEOUS_INCOME("OtherMiscellaneousIncome", "Other Miscellaneous Income", QBOAccountType.OTHER_INCOME),
    OTHER_MISCELLANEOUS_SERVICE_COST("OtherMiscellaneousServiceCost", "Other Miscellaneous Service Cost", QBOAccountType.EXPENSE),
    OTHER_PRIMARY_INCOME("OtherPrimaryIncome", "Other Primary Income", QBOAccountType.INCOME),
    OTHER_VEHICLE_EXPENSES("OtherVehicleExpenses", "Other Vehicle Expenses", QBOAccountType.OTHER_EXPENSE),
    OWNERS_EQUITY("OwnersEquity", "Owner's Equity", QBOAccountType.EQUITY),
    PAID_IN_CAPITAL_OR_SURPLUS("PaidInCapitalOrSurplus", "Paid-in Capital or Surplus", QBOAccountType.EQUITY),
    PARKING_AND_TOLLS("ParkingAndTolls", "Parking & Tolls", QBOAccountType.EXPENSE),
    PARTNER_CONTRIBUTIONS("PartnerContributions", "Partner Contributions", QBOAccountType.EQUITY),
    PARTNER_DISTRIBUTIONS("PartnerDistributions", "Partner Distributions", QBOAccountType.EQUITY),
    PARTNERS_EQUITY("PartnersEquity", "Partner's Equity", QBOAccountType.EQUITY),
    PAYROLL_CLEARING("PayrollClearing", "Payroll Clearing", QBOAccountType.OTHER_CURRENT_LIABILITY),
    PAYROLL_EXPENSES("PayrollExpenses", "Payroll Expenses", QBOAccountType.EXPENSE),
    PAYROLL_TAX_EXPENSES("PayrollTaxExpenses", "Payroll Tax Expenses", QBOAccountType.EXPENSE),
    PAYROLL_WAGE_EXPENSES("PayrollWageExpenses", "Payroll Wage Expenses", QBOAccountType.EXPENSE),
    PAYROLL_TAX_PAYABLE("PayrollTaxPayable", "Payroll Tax Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    PENALTIES_SETTLEMENTS("PenaltiesSettlements", "Penalties & Settlements", QBOAccountType.OTHER_EXPENSE),
    PERSONAL_EXPENSE("PersonalExpense", "Personal Expense", QBOAccountType.EQUITY),
    PERSONAL_INCOME("PersonalIncome", "Personal Income", QBOAccountType.EQUITY),
    PREFERRED_STOCK("PreferredStock", "Preferred Stock", QBOAccountType.EQUITY),
    PREPAID_EXPENSES("PrepaidExpenses", "Prepaid Expenses", QBOAccountType.OTHER_CURRENT_ASSET),
    PREPAID_EXPENSES_PAYABLE("PrepaidExpensesPayable", "Prepaid Expenses Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    PROMOTIONAL_MEALS("PromotionalMeals", "Promotional Meals", QBOAccountType.EXPENSE),
    PROPERTY_TAX_HOME_OFFICE("PropertyTaxHomeOffice", "Property Tax Home Office", QBOAccountType.OTHER_EXPENSE),
    RENT_AND_LEASE_HOME_OFFICE("RentAndLeaseHomeOffice", "Rent and Lease Home Office", QBOAccountType.OTHER_EXPENSE),
    RENT_OR_LEASE_OF_BUILDINGS("RentOrLeaseOfBuildings", "Rent or Lease of Buildings", QBOAccountType.EXPENSE),
    RENTS_HELD_IN_TRUST("RentsHeldInTrust", "Rents Held in Trust", QBOAccountType.BANK),
    RENTS_IN_TRUST_LIABILITY("RentsInTrustLiability", "Rents in trust - Liability", QBOAccountType.OTHER_CURRENT_LIABILITY),
    REPAIRS_AND_MAINTAINCE_HOME_OFFICE("RepairsAndMaintainceHomeOffice", "Repairs and Maintaince Home Office", QBOAccountType.OTHER_EXPENSE),
    REPAIR_MAINTENANCE("RepairMaintenance", "Repair & Maintenance", QBOAccountType.EXPENSE),
    RETAINAGE("Retainage", "Retainage", QBOAccountType.OTHER_CURRENT_ASSET),
    RETAINED_EARNINGS("RetainedEarnings", "Retained Earnings", QBOAccountType.EQUITY),
    SALES_OF_PRODUCT_INCOME("SalesOfProductIncome", "Sales of Product Income", QBOAccountType.INCOME),
    SALES_TAX_PAYABLE("SalesTaxPayable", "Sales Tax Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    SAVINGS("Savings", "Savings", QBOAccountType.BANK),
    SECURITY_DEPOSITS("SecurityDeposits", "Security Deposits", QBOAccountType.OTHER_ASSET),
    SERVICE_FEE_INCOME("ServiceFeeIncome", "Service/Fee Income", QBOAccountType.INCOME),
    SHAREHOLDER_NOTES_PAYABLE("ShareholderNotesPayable", "Shareholder Notes Payable", QBOAccountType.LONG_TERM_LIABILITY),
    SHIPPING_FREIGHT_DELIVERY("ShippingFreightDelivery", "Shipping, Freight & Delivery", QBOAccountType.EXPENSE),
    SHIPPING_FREIGHT_DELIVERY_COS("ShippingFreightDeliveryCos", "Shipping, Freight & Delivery - COS", QBOAccountType.COST_OF_GOODS_SOLD),
    STATE_LOCAL_INCOME_TAX_PAYABLE("StateLocalIncomeTaxPayable","State/Local Income Tax Payable", QBOAccountType.OTHER_CURRENT_LIABILITY),
    SUPPLIES_MATERIALS("SuppliesMaterials", "Supplies & Materials", QBOAccountType.EXPENSE),
    SUPPLIES_MATERIALS_COGS("SuppliesMaterialsCogs", "Supplies & Materials - COGS", QBOAccountType.COST_OF_GOODS_SOLD),
    TAXES_PAID("TaxesPaid", "Taxes Paid", QBOAccountType.EXPENSE),
    TAX_EXEMPT_INTEREST("TaxExemptInterest", "Tax-Exempt Interest", QBOAccountType.OTHER_INCOME),
    TRAVEL("Travel", "Travel", QBOAccountType.EXPENSE),
    TRAVEL_MEALS("TravelMeals", "Travel Meals", QBOAccountType.EXPENSE),
    TREASURY_STOCK("TreasuryStock", "Treasury Stock", QBOAccountType.EQUITY),
    TRUST_ACCOUNTS("TrustAccounts", "Trust account", QBOAccountType.BANK),
    TRUST_ACCOUNTS_LIABILITIES("TrustAccountsLiabilities", "Trust Accounts - Liabilities", QBOAccountType.OTHER_CURRENT_LIABILITY),
    UNAPPLIED_CASH_BILL_PAYMENT_EXPENSE("UnappliedCashBillPaymentExpense", "Unapplied Cash Bill Payment Expense", QBOAccountType.EXPENSE),
    UNAPPLIED_CASH_PAYMENT_INCOME("UnappliedCashPaymentIncome", "Unapplied Cash Payment Income", QBOAccountType.INCOME),
    UNDEPOSITED_FUNDS("UndepositedFunds", "Undeposited Funds", QBOAccountType.OTHER_CURRENT_ASSET),
    UTILITIES("Utilities", "Utilities", QBOAccountType.EXPENSE),

    COMMUNICATIONS("Communications", "Communication", QBOAccountType.EXPENSE),

    UTILITIES_HOME_OFFICE("UtilitiesHomeOffice", "Utilities Home Office", QBOAccountType.OTHER_EXPENSE),

    VEHICLE("Vehicle", "Vehicles", QBOAccountType.OTHER_EXPENSE), // 확인필요

    VEHICLE_INSURANCE("VehicleInsurance", "Vehicle Insurance", QBOAccountType.OTHER_EXPENSE),
    VEHICLE_LEASE("VehicleLease", "Vehicle Lease", QBOAccountType.OTHER_EXPENSE),
    VEHICLE_LOAN("VehicleLoan", "Vehicle Loan", QBOAccountType.OTHER_EXPENSE),
    VEHICLE_LOAN_INTEREST("VehicleLoanInterest", "Vehicle Loan Interest", QBOAccountType.OTHER_EXPENSE),
    VEHICLE_REGISTRATION("VehicleRegistration", "Vehicle Registration", QBOAccountType.OTHER_EXPENSE),
    VEHICLE_REPAIRS("VehicleRepairs", "Vehicle Repairs", QBOAccountType.OTHER_EXPENSE),

    VEHICLES("Vehicles", "Vehicles", QBOAccountType.FIXED_ASSET),   // 확인필요
    WASH_AND_ROAD_SERVICES("WashAndRoadServices", "Wash and Road Services", QBOAccountType.OTHER_EXPENSE),

    // 확인필요
//    WITHHOLDING_TAX_SALES("WithholdingTaxSales", "Withholding Tax Sales", QboAccountType.OTHER_CURRENT_LIABILITY),
//    WITHHOLDING_TAX_PURCHASES("WithholdingTaxPurchases"),
//    WITHHOLDING_ASSET_AMOUNT("WithholdingAssetAmount"),
//    WITHHOLDING_LIABILITY_AMOUNT("WithholdingLiabilityAmount"),
//    WITHHOLDING_TAX_SUSPENSE("WithholdingTaxSuspense"),
//    PROVISIONS_CURRENT_ASSETS("ProvisionsCurrentAssets"),
//    OTHER_CONSUMABLES("OtherConsumables"),
//    EXPENDITURE_AUTHORISATIONS_AND_LETTERS_OF_CREDIT("ExpenditureAuthorisationsAndLettersOfCredit"),
//    INTERNAL_TRANSFERS("InternalTransfers"),
//    PROVISIONS_FIXED_ASSETS("ProvisionsFixedAssets"),
//    ASSETS_IN_COURSE_OF_CONSTRUCTION("AssetsInCourseOfConstruction"),
//    PARTICIPATING_INTERESTS("ParticipatingInterests"),
//    CUMULATIVE_DEPRECIATION_ON_INTANGIBLE_ASSETS("CumulativeDepreciationOnIntangibleAssets"),
//    PROVISIONS_NON_CURRENT_ASSETS("ProvisionsNonCurrentAssets"),
//    OUTSTANDING_DUES_MICRO_SMALL_ENTERPRISE("OutstandingDuesMicroSmallEnterprise"),
//    OUTSTANDING_DUES_OTHER_THAN_MICRO_SMALL_ENTERPRISE("OutstandingDuesOtherThanMicroSmallEnterprise"),
//    GLOBAL_TAX_REFUND("GlobalTaxRefund"),
//    GLOBAL_TAX_DEFERRED("GlobalTaxDeferred"),
//    PROVISIONS_CURRENT_LIABILITIES("ProvisionsCurrentLiabilities"),
//    STAFF_AND_RELATED_LIABILITY_ACCOUNTS("StaffAndRelatedLiabilityAccounts"),
//    SOCIAL_SECURITY_AGENCIES("SocialSecurityAgencies"),
//    SUNDRY_DEBTORS_AND_CREDITORS("SundryDebtorsAndCreditors"),
//    PROVISIONS_NON_CURRENT_LIABILITIES("ProvisionsNonCurrentLiabilities"),
//    DEBTS_RELATED_TO_PARTICIPATING_INTERESTS("DebtsRelatedToParticipatingInterests"),
//    STAFF_AND_RELATED_LONG_TERM_LIABILITY_ACCOUNTS("StaffAndRelatedLongTermLiabilityAccounts"),
//    GOVERNMENT_AND_OTHER_PUBLIC_AUTHORITIES("GovernmentAndOtherPublicAuthorities"),
//    GROUP_AND_ASSOCIATES("GroupAndAssociates"),
//    INVESTMENT_GRANTS("InvestmentGrants"),
//    CASH_RECEIPT_INCOME("CashReceiptIncome"),
//    OWN_WORK_CAPITALIZED("OwnWorkCapitalized"),
//    OPERATING_GRANTS("OperatingGrants"),
//    OTHER_CURRENT_OPERATING_INCOME("OtherCurrentOperatingIncome"),
//    COST_OF_SALES("CostOfSales"),
//    CASH_EXPENDITURE_EXPENSE("CashExpenditureExpense"),
//    EXTERNAL_SERVICES("ExternalServices"),
//    OTHER_EXTERNAL_SERVICES("OtherExternalServices"),
//    PURCHASES_REBATES("PurchasesRebates"),
//    OTHER_RENTAL_COSTS("OtherRentalCosts"),
//    PROJECT_STUDIES_SURVEYS_ASSESSMENTS("ProjectStudiesSurveysAssessments"),
//    SUNDRY("Sundry"),
//    STAFF_COSTS("StaffCosts"),
//    OTHER_CURRENT_OPERATING_CHARGES("OtherCurrentOperatingCharges"),
//    EXTRAORDINARY_CHARGES("ExtraordinaryCharges"),
//    APPROPRIATIONS_TO_DEPRECIATION("AppropriationsToDepreciation"),
//    ACCRUALS_AND_DEFERRED_INCOME("AccrualsAndDeferredIncome"),
//    CURRENT_TAX_LIABILITY("CurrentTaxLiability"),
//    DEFERRED_TAX("DeferredTax"),
//    DISTRIBUTION_COSTS("DistributionCosts"),
//    INVESTMENTS("Investments"),
//    LONG_TERM_BORROWINGS("LongTermBorrowings"),
//    OTHER_INTANGIBLE_ASSETS("OtherIntangibleAssets"),
//    PREPAYMENTS_AND_ACCRUED_INCOME("PrepaymentsAndAccruedIncome"),
//    SHORT_TERM_BORROWINGS("ShortTermBorrowings"),
//    PROVISION_FOR_LIABILITIES("ProvisionForLiabilities"),
//    CALLED_UP_SHARE_CAPITAL("CalledUpShareCapital"),
//    CALLED_UP_SHARE_CAPITAL_NOT_PAID("CalledUpShareCapitalNotPaid"),
//    LAND_ASSET("LandAsset"),
//    AVAILABLE_FOR_SALE_FINANCIAL_ASSETS("AvailableForSaleFinancialAssets"),
//    PROVISION_FOR_WARRANTY_OBLIGATIONS("ProvisionForWarrantyObligations"),
//    CURRENT_PORTION_EMPLOYEE_BENEFITS_OBLIGATIONS("CurrentPortionEmployeeBenefitsObligations"),
//    LONG_TERM_EMPLOYEE_BENEFIT_OBLIGATIONS("LongTermEmployeeBenefitObligations"),
//    OBLIGATIONS_UNDER_FINANCE_LEASES("ObligationsUnderFinanceLeases"),
//    BANK_LOANS("BankLoans"),
//    INTEREST_PAYABLES("InterestPayables"),
//    GAIN_LOSS_ON_SALE_OF_INVESTMENTS("GainLossOnSaleOfInvestments"),
//    GAIN_LOSS_ON_SALE_OF_FIXED_ASSETS("GainLossOnSaleOfFixedAssets"),
//    SHARE_CAPITAL("ShareCapital"),
//    CURRENT_PORTION_OF_OBLIGATIONS_UNDER_FINANCE_LEASES("CurrentPortionOfObligationsUnderFinanceLeases"),
//    ASSETS_HELD_FOR_SALE("AssetsHeldForSale"),
//    ACCRUED_LIABILITIES("AccruedLiabilities"),
//    ACCRUED_LONG_LERM_LIABILITIES("AccruedLongLermLiabilities"),
//    ACCRUED_VACATION_PAYABLE("AccruedVacationPayable"),
//    CASH_AND_CASH_EQUIVALENTS("CashAndCashEquivalents"),
//    COMMISSIONS_AND_FEES("CommissionsAndFees"),
//    AMORTIZATION_EXPENSE("AmortizationExpense"),
//    LOSS_ON_DISCONTINUED_OPERATIONS_NET_OF_TAX("LossOnDiscontinuedOperationsNetOfTax"),
//
//    MANAGEMENT_COMPENSATION("ManagementCompensation"),
//    OTHER_SELLING_EXPENSES("OtherSellingExpenses"),
//    LIABILITIES_RELATED_TO_ASSETS_HELD_FOR_SALE("LiabilitiesRelatedToAssetsHeldForSale"),
//    LONG_TERM_DEBIT("LongTermDebit"),
//    EQUITY_IN_EARNINGS_OF_SUBSIDUARIES("EquityInEarningsOfSubsiduaries"),
//    OTHER_OPERATING_INCOME("OtherOperatingIncome"),
//    REVENUE_GENERAL("RevenueGeneral"),
//    DIVIDEND_DISBURSED("DividendDisbursed"),
//    FREIGHT_AND_DELIVERY_COS("FreightAndDeliveryCos"),
//    SHIPPING_AND_DELIVERY_EXPENSE("ShippingAndDeliveryExpense"),
//    TRAVEL_EXPENSES_GENERAL_AND_ADMIN_EXPENSES("TravelExpensesGeneralAndAdminExpenses"),
//    TRAVEL_EXPENSES_SELLING_EXPENSE("TravelExpensesSellingExpense"),
//    UNREALISED_LOSS_ON_SECURITIES_NET_OF_TAX("UnrealisedLossOnSecuritiesNetOfTax"),
//    SALES_RETAIL("SalesRetail"),
//    SALES_WHOLESALE("SalesWholesale"),
//    ACCUMULATED_OTHER_COMPREHENSIVE_INCOME("AccumulatedOtherComprehensiveIncome"),
//    ASSETS_AVAILABLE_FOR_SALE("AssetsAvailableForSale"),
//    LOSS_ON_DISPOSAL_OF_ASSETS("LossOnDisposalOfAssets"),
//    NON_CURRENT_ASSETS("NonCurrentAssets"),
//    INCOME_TAX_EXPENSE("IncomeTaxExpense"),
//    LONG_TERM_INVESTMENTS("LongTermInvestments"),
//    DIVIDENDS_PAYABLE("DividendsPayable"),
//    TRADE_AND_OTHER_RECEIVABLES("TradeAndOtherReceivables"),
//    TRADE_AND_OTHER_PAYABLES("TradeAndOtherPayables"),
//    CURRENT_LIABILITIES("CurrentLiabilities"),
//    SAVINGS_BY_TAX_SCHEME("SavingsByTaxScheme"),
//    BORROWING_COST("BorrowingCost"),
//    DEPLETION("Depletion"),
//    EXCEPTIONAL_ITEMS("ExceptionalItems"),
//    PRIOR_PERIOD_ITEMS("PriorPeriodItems"),
//    EXTRAORDINARY_ITEMS("ExtraordinaryItems"),
//    MAT_CREDIT("MatCredit"),
//    OTHER_FREE_RESERVES("OtherFreeReserves"),
//    CAPITAL_RESERVES("CapitalReserves"),
//    FUNDS("Funds"),
//    MONEY_RECEIVED_AGAINST_SHARE_WARRANTS("MoneyReceivedAgainstShareWarrants"),
//    SHARE_APPLICATION_MONEY_PENDING_ALLOTMENT("ShareApplicationMoneyPendingAllotment"),
//    DEFERRED_TAX_LIABILITIES("DeferredTaxLiabilities"),
//    OTHER_LONG_TERM_PROVISIONS("OtherLongTermProvisions"),
//    CAPITAL_WIP("CapitalWip"),
//    INTANGIBLE_ASSETS_UNDER_DEVELOPMENT("IntangibleAssetsUnderDevelopment"),
//    OTHER_LONG_TERM_INVESTMENTS("OtherLongTermInvestments"),
//    LONG_TERM_LOANS_AND_ADVANCES_TO_RELATED_PARTIES("LongTermLoansAndAdvancesToRelatedParties"),
//    OTHER_LONG_TERM_LOANS_AND_ADVANCES("OtherLongTermLoansAndAdvances"),
//    SHORT_TERM_INVESTMENTS_IN_RELATED_PARTIES("ShortTermInvestmentsInRelatedParties"),
//    OTHER_EARMARKED_BANK_ACCOUNTS("OtherEarmarkedBankAccounts"),
//    SHORT_TERM_LOANS_AND_ADVANCES_TO_RELATED_PARTIES("ShortTermLoansAndAdvancesToRelatedParties"),
//    DEFERRED_TAX_EXPENSE("DeferredTaxExpense"),
//    INCOME_TAX_OTHER_EXPENSE("IncomeTaxOtherExpense"),
//    DUTIES_AND_TAXES("DutiesAndTaxes"),
//    BAL_WITH_GOVT_AUTHORITIES("BalWithGovtAuthorities"),
//    TAX_ROUNDOFF_GAIN_OR_LOSS("TaxRoundoffGainOrLoss"),
//    OTHER_DEBTORS("OtherDebtors"),
//    RENT_A_ROOM_RELIEF_RENTS_RECEIVED("RentARoomReliefRentsReceived"),
//    UK_TAXES_WITHHELD("UkTaxesWithheld"),
//    FOREIGN_TAXES_INCURRED("ForeignTaxesIncurred"),
//    PREMIUMS_RECEIVED("PremiumsReceived"),
//    PREMIUMS_PAID("PremiumsPaid"),
//    FINANCE_COSTS_RESTRICTED("FinanceCostsRestricted"),
//    CARRIED_FORWARD_RELIEF("CarriedForwardRelief"),
//    RENT_A_ROOM_RELIEF_RELIEF_CLAIMED("RentARoomReliefReliefClaimed");
;


    companion object {
        fun fromValue(v: String): QBOAccountSubType {
            for (c in entries) {
                if (c.value == v) {
                    return c
                }
            }
            throw IllegalArgumentException(v)
        }

        fun fromUI(v: String): QBOAccountSubType {
            for (c in entries) {
                if (c.displayName == v) {
                    return c
                }
            }
            throw IllegalArgumentException(v)
        }
    }
}



@Converter
class QboAccountSubTypeConverter : AttributeConverter<QBOAccountSubType, String> {
    override fun convertToDatabaseColumn(attribute: QBOAccountSubType?): String? {
        return attribute?.value
    }

    override fun convertToEntityAttribute(dbData: String?): QBOAccountSubType? {
        return dbData?.let { engName ->
            QBOAccountSubType.entries.find { it.value == engName }
        }
    }
}
