package com.abc.us.accounting.rentals.lease.model.v2

data class RentalFinancialLeaseHistoryDataV2(
    val orderId: String,
    val orderItemId: String,
    val customerId: String,
    val serialNumber: String,
    val contractId: String,
    val materialId: String,
    val materialSeriesCode: String,
    val baseDate: String,
    val contractDate: String,
    val contractEndDate: String,
    val contractPeriod: Int,
    val initialBookValue: Double,
    val interestRate: Double,
    val rentalAmount: Double,
    val initialPresentValue: Double,
    val initialCurrentDifference: Double,
    val depreciationCount: Int,
    val depreciationBookValue: Double,
    val depreciationPresentValue: Double,
    val depreciationCurrentDifference: Double,
    val depreciationInterestIncome: Double,
    val cumulativeInterestIncome: Double,
    val createTime: String,
    val docHashCode: String,
    val rentalEventType: String,
    val currency: String,
    val depreciationYearMonth: String,
    val depreciationBillYearMonth: String?,
    val rentalAmountForGoods: Double,
    val totalCnt: Long
)
