CREATE TABLE IF NOT EXISTS "collect_bank_reconcil"
(
    "hash_code"                varchar not null primary key,
    "reconcil_id"              varchar,
    "reconcil_line_number"     integer not null,
    "currency"                 varchar,
    "reconcil_to_account_code" varchar,
    "total_amount"             NUMERIC(38,2),
    "line_amount"              NUMERIC(38,2),
    "detail_type"              varchar,
    "payment_method"           varchar,
    "account_code"             varchar,
    "entity_name"              varchar,
    "entity_value"             varchar,
    "txn_id"                   varchar,
    "txn_type"                 varchar,
    "txn_date"                 date,
    "tax_code"                 varchar,
    "total_tax"                NUMERIC(38,2),
    "private_note"             varchar,
    "create_time"              timestamp(6) with time zone,
    "update_time"              timestamp(6) with time zone,
    "is_active"                char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_channel"
(
    "hash_code"      varchar not null primary key,
    "entity"         varchar,
    "field"          varchar,
    "value"          varchar,
    "channel_id"     varchar,
    "channel_name"   varchar,
    "channel_type"   varchar,
    "channel_detail" varchar,
    "create_time"    timestamp(6) with time zone,
    "update_time"    timestamp(6) with time zone,
    "is_active"      char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_charge"
(
    "hash_code"     varchar not null primary key,

    "total_price"           NUMERIC(38,2),
    "discount_price"        NUMERIC(38,2),
    "item_price"            NUMERIC(38,2),
    "prepaid_amount"        NUMERIC(38,2),
    "tax"                   NUMERIC(38,2),
    "registration_price"    NUMERIC(38,2),
    "currency"              varchar,
    "is_tax_exempt"         char check (is_tax_exempt = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),

    "invoice_id"    varchar,
    "charge_id"     varchar,
    "charge_status" varchar,
    "billing_cycle" integer,
    "target_month"  varchar,
    "contract_id"   varchar,
    "receipt_id"    varchar,
    "start_date"    date,
    "end_date"      date,
    "create_time"   timestamp(6) with time zone,
    "update_time"   timestamp(6) with time zone,
    "is_active"     char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_charge_item"
(
    "hash_code"        varchar not null primary key,
    "entity"           varchar,
    "field"            varchar,
    "value"            varchar,

    "total_price"           NUMERIC(38,2),
    "discount_price"        NUMERIC(38,2),
    "item_price"            NUMERIC(38,2),
    "prepaid_amount"        NUMERIC(38,2),
    "tax"                   NUMERIC(38,2),
    "registration_price"    NUMERIC(38,2),
    "currency"              varchar,
    "is_tax_exempt"         char check (is_tax_exempt = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),

    "invoice_id"        varchar,
    "charge_id"         varchar,
    "charge_item_id"    varchar,
    "charge_item_type"  varchar,
    "service_flow_id"   varchar,
    "quantity"          integer,
    "receipt_id"        varchar,
    "create_time"       timestamp(6) with time zone,
    "update_time"       timestamp(6) with time zone,
    "is_active"         char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_contract"
(
    "hash_code"             varchar not null primary key,
    "entity"                varchar,
    "field"                 varchar,
    "value"                 varchar,
    "contract_id"           varchar,
    "channel_contract_id"   varchar,
    "channel_order_item_id" varchar,
    "is_signed"             char check (is_signed = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),
    "signed_time"           timestamp(6) with time zone,
    "form_id"               varchar,
    "revision"              integer,
    "rental_code"           varchar,
    "customer_id"           varchar,
    "order_id"              varchar,
    "order_item_id"         varchar,
    "material_id"           varchar,
    "start_date"            date,
    "end_date"              date,
    "duration_in_months"    integer,
    "contract_status"       varchar,
    "create_time"           timestamp(6) with time zone,
    "update_time"           timestamp(6) with time zone,
    "is_active"             char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_customer"
(
    "hash_code"            varchar not null primary key,
    "customer_id"          varchar,
    "title_name"           varchar,
    "first_name"           varchar,
    "middle_name"          varchar,
    "last_name"            varchar,
    "family_name"          varchar,
    "name_suffix"          varchar,
    "fully_qualified_name" varchar,
    "company_name"         varchar,
    "display_name"         varchar,
    "user_id"              varchar,
    "primary_phone"        varchar,
    "alternate_phone"      varchar,
    "mobile"               varchar,
    "fax"                  varchar,
    "primary_email"        varchar,
    "alternate_email"      varchar,
    "web_addr"             varchar,
    "entity"               varchar,
    "field"                varchar,
    "value"                varchar,
    "channel_customer_id"  varchar,
    "customer_status"      varchar,
    "channel_type"         varchar,
    "customer_type"        varchar,
    "is_tax_liability"     char check (is_tax_liability = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),
    "currency"             varchar(3),
    "installation_id"      varchar,
    "referrer_code"        varchar,
    "create_time"          timestamp(6) with time zone,
    "update_time"          timestamp(6) with time zone,
    "is_active"            char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);


CREATE TABLE IF NOT EXISTS "collect_location"
(
    "hash_code"            varchar not null primary key,
    "entity"               varchar,
    "field"                varchar,
    "value"                varchar,
    "location_id"          varchar,
    "branch_id"            varchar,
    "warehouse_id"         varchar,
    "latitude"             double precision,
    "longitude"            double precision,
    "address1"             varchar,
    "address2"             varchar,
    "alternate_email"      varchar,
    "alternate_phone"      varchar,
    "city"                 varchar,
    "company_name"         varchar,
    "country"              varchar,
    "country_code"         varchar,
    "county"               varchar,
    "display_name"         varchar,
    "family_name"          varchar,
    "fax"                  varchar,
    "first_name"           varchar,
    "fully_qualified_name" varchar,
    "last_name"            varchar,
    "location_remark"      varchar,
    "middle_name"          varchar,
    "mobile"               varchar,
    "name_suffix"          varchar,
    "primary_email"        varchar,
    "primary_phone"        varchar,
    "state"                varchar,
    "title_name"           varchar,
    "user_id"              varchar,
    "web_addr"             varchar,
    "zip_code"             varchar,
    "create_time"          timestamp(6) with time zone,
    "update_time"          timestamp(6) with time zone,
    "is_active"            char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_installation"
(
    "hash_code"            varchar not null primary key,
    "entity"               varchar,
    "field"                varchar,
    "value"                varchar,

    "latitude"             double precision,
    "longitude"            double precision,
    "installation_time"    timestamp(6) with time zone,
    "warranty_end_time"    timestamp(6) with time zone,
    "warranty_start_time"  timestamp(6) with time zone,
    "address1"             varchar,
    "address2"             varchar,
    "alternate_email"      varchar,
    "alternate_phone"      varchar,
    "branch_id"            varchar,
    "city"                 varchar,
    "company_name"         varchar,
    "country"              varchar,
    "country_code"         varchar,
    "county"               varchar,
    "display_name"         varchar,
    "family_name"          varchar,
    "fax"                  varchar,
    "first_name"           varchar,
    "fully_qualified_name" varchar,
    "install_id"           varchar,
    "last_name"            varchar,
    "location_remark"      varchar,
    "middle_name"          varchar,
    "mobile"               varchar,
    "name_suffix"          varchar,
    "order_item_id"        varchar,
    "primary_email"        varchar,
    "primary_phone"        varchar,
    "serial_number"        varchar,
    "service_flow_id"      varchar,
    "state"                varchar,
    "technician_id"        varchar,
    "title_name"           varchar,
    "user_id"              varchar,
    "warehouse_id"         varchar,
    "water_type"           varchar,
    "web_addr"             varchar,
    "zip_code"             varchar,
    "create_time"          timestamp(6) with time zone,
    "update_time"          timestamp(6) with time zone,
    "is_active"            char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_material"
(
    "hash_code"              varchar not null primary key,
    "entity"                 varchar,
    "field"                  varchar,
    "value"                  varchar,
    "feature_code"           varchar,
    "description"            varchar,
    "filter_type"            varchar,
    "installation_type"      varchar,
    "material_brand_name"    varchar,
    "material_category_code" varchar not null,
    "material_id"            varchar not null,
    "material_model_name"    varchar,
    "material_name"          varchar not null,
    "material_series_code"   varchar,
    "material_type"          varchar not null,
    "product_type"           varchar not null,
    "create_time"            timestamp(6) with time zone,
    "update_time"            timestamp(6) with time zone,
    "is_active"              char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);
CREATE TABLE IF NOT EXISTS "collect_order"
(
    "hash_code"          varchar not null primary key,
    "entity"             varchar,
    "field"              varchar,
    "value"              varchar,
    "channel_id"         varchar,
    "channel_order_id"   varchar,
    "customer_id"        varchar,
    "order_id"           varchar,
    "order_product_type" varchar,
    "receipt_id"         varchar,
    shipping_id          varchar,
    "referrer_code"      varchar,
    "order_create_time"  timestamp(6) with time zone,
    "order_update_time"  timestamp(6) with time zone,
    "update_time"        timestamp(6) with time zone,
    "create_time"        timestamp(6) with time zone,
    "is_active"          char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);


CREATE TABLE IF NOT EXISTS "collect_order_item"
(
    "hash_code"             varchar not null primary key,
    "entity"                varchar,
    "field"                 varchar,
    "value"                 varchar,

    "total_price"           NUMERIC(38,2),
    "discount_price"        NUMERIC(38,2),
    "item_price"            NUMERIC(38,2),
    "prepaid_amount"        NUMERIC(38,2),
    "tax"                   NUMERIC(38,2),
    "registration_price"    NUMERIC(38,2),
    "currency"              varchar,
    "is_tax_exempt"         char check (is_tax_exempt = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),

    "quantity"              integer,
    "channel_order_id"      varchar,
    "channel_order_item_id" varchar,
    "contract_id"           varchar,
    "install_id"            varchar,
    shipping_id             varchar,
    "material_id"           varchar,
    "order_id"              varchar,
    "order_item_id"         varchar,
    "order_item_status"     varchar,
    "order_item_type"       varchar,
    "create_time"           timestamp(6) with time zone,
    "update_time"           timestamp(6) with time zone,
    "is_active"             char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_receipt"
(
    "hash_code"                varchar not null primary key,
    "entity"                   varchar,
    "field"                    varchar,
    "value"                    varchar,

    "title_name"           varchar,
    "first_name"           varchar,
    "middle_name"          varchar,
    "last_name"            varchar,
    "family_name"          varchar,
    "name_suffix"          varchar,
    "fully_qualified_name" varchar,
    "company_name"         varchar,
    "display_name"         varchar,
    "user_id"              varchar,
    "primary_phone"        varchar,
    "alternate_phone"      varchar,
    "mobile"               varchar,
    "fax"                  varchar,
    "primary_email"        varchar,
    "alternate_email"      varchar,
    "web_addr"             varchar,

    "branch_id"            varchar,
    "warehouse_id"         varchar,
    "latitude"             double precision,
    "longitude"            double precision,
    "city"                 varchar,
    "country"              varchar,
    "country_code"         varchar,
    "zip_code"             varchar,
    "state"                varchar,
    "county"               varchar,
    "address1"             varchar,
    "address2"             varchar,
    "location_remark"      varchar,

    "total_price"           NUMERIC(38,2),
    "discount_price"        NUMERIC(38,2),
    "item_price"            NUMERIC(38,2),
    "prepaid_amount"        NUMERIC(38,2),
    "tax"                   NUMERIC(38,2),
    "registration_price"    NUMERIC(38,2),
    "currency"              varchar,
    "is_tax_exempt"         char check (is_tax_exempt = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),

    "invoice_id"               varchar,
    "receipt_id"               varchar,
    "charge_id"                varchar,
    "deposit_id"               varchar,
    "transaction_id"           varchar,
    "installment_months"       integer,
    "item_monthly_price"       NUMERIC(38,2),
    "monthly_discount_price"   NUMERIC(38,2),
    "monthly_tax"              NUMERIC(38,2),
    "monthly_total_price"      NUMERIC(38,2),
    "subscription_receipt_day" integer,
    "receipt_time"             timestamp(6) with time zone,
    "billing_type"             varchar,
    "card_number"              varchar,
    "card_type"                varchar,
    "receipt_method"           varchar,
    "remark"                   varchar,
    "create_time"              timestamp(6) with time zone,
    "update_time"              timestamp(6) with time zone,
    "is_active"                char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);


CREATE TABLE IF NOT EXISTS "collect_deposit"
(
    "hash_code"                       varchar not null primary key,
    "entity"                          varchar,
    "field"                           varchar,
    "value"                           varchar,
    "transaction_id"                  varchar,
    "deposit_id"                      varchar,
    "currency"                        varchar,
    "deposit_date"                    date,
    "amount"                          varchar,
    "adjustments_fee_amount"          varchar,
    "adjustments_gross_amount"        varchar,
    "charges_fee_amount"              varchar,
    "charges_gross_amount"            varchar,
    "refunds_fee_amount"              varchar,
    "refunds_gross_amount"            varchar,
    "reserved_funds_fee_amount"       varchar,
    "reserved_funds_gross_amount"     varchar,
    "retried_deposits_fee_amount"     varchar,
    "retried_deposits_gross_aamount"  varchar,
    "sales_fee_amount"                varchar,
    "sales_gross_amount"              varchar,
    "fees"                            varchar,
    "gross"                           varchar,
    "net"                             varchar,
    "create_time"                     timestamp(6) with time zone,
    "update_time"                     timestamp(6) with time zone,
    "is_active"                       char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_service_flow"
(
    "hash_code"                  varchar not null primary key,
    "billing_id"                 varchar,
    "customer_service_id"        varchar,
    "customer_service_ticket_id" varchar,
    "order_id"                   varchar,
    "order_item_id"              varchar,
    "service_flow_id"            varchar,
    "service_status"             varchar,
    "service_type"               varchar,
    "work_id"                    varchar,
    "cancel_time"                timestamp(6) with time zone,
    "create_time"                timestamp(6) with time zone,
    "update_time"                timestamp(6) with time zone,
    "is_active"                  char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_tax_line"
(
    "hash_code"             varchar not null primary key,
    "entity"                varchar,
    "field"                 varchar,
    "value"                 varchar,
    "price"                 NUMERIC(38,2),
    "rate"                  NUMERIC(38, 4),
    "title"                 varchar,
    "sales_tax_type"        varchar,
    "create_time" timestamp(6) with time zone,
    "update_time" timestamp(6) with time zone,
    "is_active"   char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_shipping"
(
    "hash_code"             varchar not null primary key,
    shipping_id             varchar,
    service_flow_id         varchar,
    company_name            varchar,
    company_code            varchar,
    tracking_id             varchar,
    tracking_url            varchar,
    shipment_date           timestamp,
    delivery_date           timestamp,
    estimated_delivery_date date,
    "create_time" timestamp(6) with time zone,
    "update_time" timestamp(6) with time zone,
    "is_active"   char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_vendor"
(
    "hash_code"            varchar not null primary key,
    "entity"               varchar,
    "field"                varchar,
    "value"                varchar,

    "title_name"           varchar,
    "first_name"           varchar,
    "middle_name"          varchar,
    "last_name"            varchar,
    "family_name"          varchar,
    "name_suffix"          varchar,
    "fully_qualified_name" varchar,
    "company_name"         varchar,
    "display_name"         varchar,
    "user_id"              varchar,
    "primary_phone"        varchar,
    "alternate_phone"      varchar,
    "mobile"               varchar,
    "fax"                  varchar,
    "primary_email"        varchar,
    "alternate_email"      varchar,
    "web_addr"             varchar,

    "branch_id"            varchar,
    "warehouse_id"         varchar,
    "latitude"             double precision,
    "longitude"            double precision,
    "city"                 varchar,
    "country"              varchar,
    "country_code"         varchar,
    "zip_code"             varchar,
    "state"                varchar,
    "county"               varchar,
    "address1"             varchar,
    "address2"             varchar,
    "location_remark"      varchar,

    "acct_num"             varchar,
    "business_number"      varchar,
    "company_id"           varchar,
    "currency"             varchar,
    "department_code"      varchar,
    "department_name"      varchar,
    "description"          varchar,
    "employer_code"        varchar,
    "remark"               varchar,
    "tax_identifier"       varchar,
    "terms"                varchar,
    "vendor_id"            varchar,
    "create_time"          timestamp(6) with time zone,
    "update_time"          timestamp(6) with time zone,
    "is_active"           char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);


CREATE TABLE IF NOT EXISTS "collect_inventory_valuation"
(
    "hash_code"             varchar not null primary key,
    "issued_time"           timestamp(6) with time zone,
    "material_id"           varchar,
    "currency"              varchar(3),
    "movement_type"         varchar ,
    "grade_type"            varchar,
    "stock_avg_unit_price"  NUMERIC(38,2),
    "moving_avg_method"     varchar,
    "remark"                varchar,
    "create_time"           timestamp(6) with time zone,
    "update_time"           timestamp(6) with time zone,
    "is_active"             char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);

CREATE TABLE IF NOT EXISTS "collect_promotion"
(
    "hash_code"             varchar not null primary key,
    "entity"                varchar,
    "field"                 varchar,
    "value"                 varchar,
    promotion_id            varchar,
    promotion_name          varchar,
    promotion_description   varchar,
    start_date              timestamp(6) with time zone,
    end_date                timestamp(6) with time zone,
    discount_price          NUMERIC(38,2),
    discount_target_type    varchar,
    discount_type           varchar,
    promotion_cycles        varchar,
    promotion_type          varchar,
    offer_type              varchar,
    material_id             varchar,
    amount                  NUMERIC(38,2),
    rate                    NUMERIC(38,4),
    "create_time"           timestamp(6) with time zone,
    "update_time"           timestamp(6) with time zone,
    "is_active"             char check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar]))
);