CREATE TABLE IF NOT EXISTS  "if_purchase_order"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "purchase_order_id" varchar NOT NULL,
    "purchase_order_status" varchar NOT NULL,
    "vendor_id" varchar,
    "customer_id" varchar,
    "create_time" timestamp(6) with time zone NOT NULL
                                   );
CREATE INDEX "ix_purchase_order_create_time" ON "if_purchase_order" ("create_time" DESC);
COMMENT ON TABLE "if_purchase_order" IS '발주 정보(History)';
COMMENT ON COLUMN "if_purchase_order"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_purchase_order"."purchase_order_id" IS '발주 ID';
COMMENT ON COLUMN "if_purchase_order"."purchase_order_status" IS '구매 주문 상태';
COMMENT ON COLUMN "if_purchase_order"."vendor_id" IS '자재 공급자';
COMMENT ON COLUMN "if_purchase_order"."customer_id" IS '자재 수급자';
COMMENT ON COLUMN "if_purchase_order"."create_time" IS '원본 레코드가 최초생성시 create_time, 수정시 update_time 입력';


CREATE TABLE IF NOT EXISTS  "if_purchase_order_item"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "purchase_order_id" varchar NOT NULL,
    "purchase_order_item_id" varchar NOT NULL,
    "material_id" varchar NOT NULL,
    "quantity" int NOT NULL,
    "unit_price" numeric(38,2) NOT NULL,
    "currency" char(3) NOT NULL,
    "create_time" timestamp(6) with time zone NOT NULL
                                   );
CREATE INDEX "ix_purchase_order_item_create_time" ON "if_purchase_order_item" ("create_time" DESC);
COMMENT ON TABLE "if_purchase_order_item" IS '발주 품목 정보(History)';
COMMENT ON COLUMN "if_purchase_order_item"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_purchase_order_item"."purchase_order_id" IS '발주 ID';
COMMENT ON COLUMN "if_purchase_order_item"."purchase_order_item_id" IS '발주 품목 ID';
COMMENT ON COLUMN "if_purchase_order_item"."material_id" IS '자재 ID';
COMMENT ON COLUMN "if_purchase_order_item"."quantity" IS '발주 수량';
COMMENT ON COLUMN "if_purchase_order_item"."unit_price" IS '발주 단가';
COMMENT ON COLUMN "if_purchase_order_item"."currency" IS '통화 코드';
COMMENT ON COLUMN "if_purchase_order_item"."create_time" IS '원본 레코드가 최초생성시 create_time, 수정시 update_time 입력';


CREATE TABLE IF NOT EXISTS  "if_inventory_movement"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_warehouse_id" varchar NOT NULL,
    "destination_warehouse_id" varchar,
    "warehouse_transfer_id" varchar,
    "transfer_status" varchar,
    "movement_category" varchar NOT NULL,
    "movement_group" varchar NOT NULL,
    "movement_type" varchar NOT NULL,
    "service_flow_id" varchar,
    "inbound_purchase_order_item_id" varchar,
    "inbound_bl_no" varchar,
    "material_id" varchar not null,
    "grade" varchar NOT NULL,
    "quantity" int NOT NULL,
    "create_time" timestamp(6) with time zone NOT NULL
                                   );
CREATE INDEX "ix_inventory_movement_create_time" ON "if_inventory_movement" ("create_time" DESC);
COMMENT ON COLUMN "if_inventory_movement"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_inventory_movement"."source_warehouse_id" IS '입고 창고, 출고 출발지 창고 ID';
COMMENT ON COLUMN "if_inventory_movement"."destination_warehouse_id" IS '출고 목적지 창고 ID(창고간 이동시)';
COMMENT ON COLUMN "if_inventory_movement"."warehouse_transfer_id" IS '창고간 이동 ID';
COMMENT ON COLUMN "if_inventory_movement"."transfer_status" IS '창고간 이동 상태(InventoryMovementTransferStatus)';
COMMENT ON COLUMN "if_inventory_movement"."movement_category" IS '수불 분류(MovementCategory)';
COMMENT ON COLUMN "if_inventory_movement"."movement_group" IS '수불 그룹(MovementGroup)';
COMMENT ON COLUMN "if_inventory_movement"."movement_type" IS '수불 유형(MovementType)';
COMMENT ON COLUMN "if_inventory_movement"."service_flow_id" IS 'OMS service flow id';
COMMENT ON COLUMN "if_inventory_movement"."inbound_purchase_order_item_id" IS '입고 시 발주 품목 ID';
COMMENT ON COLUMN "if_inventory_movement"."inbound_bl_no" IS '입고 시 B/L 번호(SAP Invoice의 순단가 확인용)';
COMMENT ON COLUMN "if_inventory_movement"."material_id" IS '자재 ID';
COMMENT ON COLUMN "if_inventory_movement"."grade" IS '자재 등급';
COMMENT ON COLUMN "if_inventory_movement"."quantity" IS '수불 발생 수량';
COMMENT ON COLUMN "if_inventory_movement"."create_time" IS '수불 발생 일시';

CREATE TABLE IF NOT EXISTS  "if_aging_range"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "range_id" varchar NOT NULL,
    "label" varchar NOT NULL,
    "min_aging_days" integer NOT NULL,
    "max_aging_days" integer,
    "is_active" char NOT NULL CONSTRAINT if_aging_range_is_active_check check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),
    "create_time" timestamp(6) with time zone NOT NULL
                                   );
CREATE INDEX "ix_aging_range_create_time" ON "if_aging_range" ("create_time" DESC);
COMMENT ON TABLE "if_aging_range" IS '에이징 범위 정보(History)';
COMMENT ON COLUMN "if_aging_range"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_aging_range"."range_id" IS '범위 고유 ID';
COMMENT ON COLUMN "if_aging_range"."label" IS '에이징 범위를 나타내는 레이블';
COMMENT ON COLUMN "if_aging_range"."min_aging_days" IS '에이징 범위 시작 일자';
COMMENT ON COLUMN "if_aging_range"."max_aging_days" IS '에이징 범위 종료 일자';
COMMENT ON COLUMN "if_aging_range"."is_active" IS '에이징 범위 사용 여부 (Y/N)';
COMMENT ON COLUMN "if_aging_range"."create_time" IS '원본 레코드가 최초생성시 create_time, 수정시 update_time 입력';

CREATE TABLE IF NOT EXISTS  "if_warehouse_inventory_age_snapshot"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "warehouse_id" varchar NOT NULL,
    "material_id" varchar NOT NULL,
    "grade" varchar NOT NULL,
    "min_aging_days" int NOT NULL,
    "max_aging_days" int,
    "quantity" int NOT NULL,
    "create_time" timestamp(6) with time zone NOT NULL
                                   );
CREATE INDEX "ix_warehouse_inventory_age_snapshot_create_time" ON "if_warehouse_inventory_age_snapshot" ("create_time" DESC);
COMMENT ON TABLE "if_warehouse_inventory_age_snapshot" IS '창고의 자재별 재고 보유 기간 정보';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."warehouse_id" IS '창고 ID';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."material_id" IS '자재 ID';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."grade" IS '자재 등급';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."min_aging_days" IS '보유기간 범위 최소값';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."max_aging_days" IS '보유기간 범위 최대값';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."quantity" IS '자재 수량';
COMMENT ON COLUMN "if_warehouse_inventory_age_snapshot"."create_time" IS '측정 기준 일시(스냅샷 일시)';

CREATE TABLE IF NOT EXISTS  "if_warehouse"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "warehouse_id" varchar NOT NULL,
    "parent_warehouse_id" varchar,
    "name" varchar NOT NULL,
    "warehouse_type" varchar NOT NULL,
    "time_zone" varchar NOT NULL,
    "is_active" char NOT NULL CONSTRAINT if_warehouse_is_active_check check (is_active = ANY (ARRAY ['N'::bpchar, 'Y'::bpchar])),
    "create_time" timestamp(6) with time zone NOT NULL
                                   );
CREATE INDEX "ix_warehouse_create_time" ON "if_warehouse" ("create_time" DESC);
COMMENT ON TABLE "if_warehouse" IS '창고 정보(History)';
COMMENT ON COLUMN "if_warehouse"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_warehouse"."warehouse_id" IS '창고 ID';
COMMENT ON COLUMN "if_warehouse"."parent_warehouse_id" IS '상위 창고 ID';
COMMENT ON COLUMN "if_warehouse"."name" IS '창고 이름';
COMMENT ON COLUMN "if_warehouse"."warehouse_type" IS '창고 유형';
COMMENT ON COLUMN "if_warehouse"."time_zone" IS 'Time Zone Id';
COMMENT ON COLUMN "if_warehouse"."is_active" IS '창고 사용 여부 (Y/N)';
COMMENT ON COLUMN "if_warehouse"."create_time" IS '원본 레코드가 최초생성시 create_time, 수정시 update_time 입력';


CREATE TABLE IF NOT EXISTS  "if_purchase_order_invoice"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "purchase_order_id" varchar NOT NULL,
    "invoice_no" varchar NOT NULL,
    "bl_no" varchar,
    "incoterms" char(3),
    "consignee_name" varchar NOT NULL,
    "consignee_address" varchar,
    "consignee_city" varchar,
    "consignee_postal_code" varchar,
    "consignee_manager" varchar NOT NULL,
    "consignee_phone" varchar,
    "consignee_email" varchar,
    "shipper_name" varchar NOT NULL,
    "shipper_address" varchar,
    "shipper_city" varchar,
    "shipper_postal_code" varchar,
    "shipper_manager" varchar NOT NULL,
    "shipper_phone" varchar,
    "shipper_email" varchar,
    "notify_party_name" varchar,
    "notify_party_address" varchar,
    "notify_party_city" varchar,
    "notify_party_postal_code" varchar,
    "notify_party_manager" varchar,
    "notify_party_email" varchar,
    "notify_party_phone" varchar,
    "port_of_loading" varchar NOT NULL,
    "port_of_discharge" varchar NOT NULL,
    "ocean_vessel" varchar,
    "voyage_no" varchar,
    "onboard_date" date,
    "invoice_date" date NOT NULL,
    "remark" text,
    "total_quantity" int NOT NULL,
    "total_amount" numeric(38,2) NOT NULL,
    "currency" char(3) NOT NULL,
    "create_time" timestamp(6) with time zone DEFAULT (now())
    );
CREATE INDEX "ix_purchase_order_invoice_create_time" ON "if_purchase_order_invoice" ("create_time" DESC);
COMMENT ON TABLE "if_purchase_order_invoice" IS '발주 Invoice Header 정보';
COMMENT ON COLUMN "if_purchase_order_invoice"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_purchase_order_invoice"."purchase_order_id" IS '발주 ID(SAP BSTKD)';
COMMENT ON COLUMN "if_purchase_order_invoice"."invoice_no" IS 'Invoice 번호(SAP CINO)';
COMMENT ON COLUMN "if_purchase_order_invoice"."bl_no" IS 'B/L 번호(SAP BLNO)';
COMMENT ON COLUMN "if_purchase_order_invoice"."incoterms" IS '국제상업거래조건(SAP INCO1)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_name" IS '수취 회사명(SAP CNAME)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_address" IS '수취인 상세 주소(SAP CSTREET)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_city" IS '수취인 도시(SAP CCITY1)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_postal_code" IS '수취인 우편번호(SAP CPSTLZ)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_manager" IS '수취 회사 담당자 이름(SAP CPNAME)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_phone" IS '수취인 연락처(SAP CPHONE)';
COMMENT ON COLUMN "if_purchase_order_invoice"."consignee_email" IS '수취인 이메일(SAP CEMAIL)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_name" IS '발송 회사명(SAP NAME2)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_address" IS '발송인 상세 주소(SAP STREET)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_city" IS '발송인 도시(SAP CITY1)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_postal_code" IS '발송인 우편번호(SAP PSTLZ)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_manager" IS '발송 회사 담당자(SAP NAME2)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_phone" IS '발송인 연락처(SAP PHONE)';
COMMENT ON COLUMN "if_purchase_order_invoice"."shipper_email" IS '발송인 이메일(SAP EMAIL)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_name" IS '화물 도착 시 통지 회사명(SAP NNAME)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_address" IS '화물 도착 시 통지 회사 상세 주소(SAP NSTREET)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_city" IS '화물 도착 시 통지 회사 도시(SAP NCITY1)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_postal_code" IS '화물 도착 시 통지 회사 우편번호(SAP NPSTLZ)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_manager" IS '화물 도착 시 통지 회사 담당자(SAP NPNAME)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_email" IS '화물 도착 시 통지 회사 이메일(SAP NEMAIL)';
COMMENT ON COLUMN "if_purchase_order_invoice"."notify_party_phone" IS '화물 도착 시 통지 회사 전화번호(SAP NPHONE)';
COMMENT ON COLUMN "if_purchase_order_invoice"."port_of_loading" IS '출발 항구(SAP KNATX)';
COMMENT ON COLUMN "if_purchase_order_invoice"."port_of_discharge" IS '도착 항구(SAP KNETX)';
COMMENT ON COLUMN "if_purchase_order_invoice"."ocean_vessel" IS '선박 이름(SAP VESLI)';
COMMENT ON COLUMN "if_purchase_order_invoice"."voyage_no" IS '항해 번호(SAP VOYNO)';
COMMENT ON COLUMN "if_purchase_order_invoice"."onboard_date" IS '출항일(SAP ONBDT)';
COMMENT ON COLUMN "if_purchase_order_invoice"."invoice_date" IS 'Invoice 발행일(SAP IVDAT)';
COMMENT ON COLUMN "if_purchase_order_invoice"."remark" IS '비고(SAP REMARK)';
COMMENT ON COLUMN "if_purchase_order_invoice"."total_quantity" IS '총수량(SAP TOTCNT)';
COMMENT ON COLUMN "if_purchase_order_invoice"."total_amount" IS '총 금액(SAP TOTAMT)';
COMMENT ON COLUMN "if_purchase_order_invoice"."currency" IS '통화 코드(SAP WAERK)';
COMMENT ON COLUMN "if_purchase_order_invoice"."create_time" IS 'SAP 조회 일시';

CREATE TABLE IF NOT EXISTS  "if_purchase_order_invoice_item"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "invoice_no" varchar(25) NOT NULL,
    "invoice_item_id" varchar(6) NOT NULL,
    "description" varchar(40) NOT NULL,
    "manufacturer_code" varchar(18) NOT NULL,
    "material_id" varchar NOT NULL,
    "model_name" varchar(100) NOT NULL,
    "sales_unit" varchar(3) NOT NULL,
    "quantity" int NOT NULL,
    "unit_price" numeric(38,2) NOT NULL,
    "total_amount" numeric(38,2) NOT NULL,
    "currency" char(3) NOT NULL,
    "create_time" timestamp(6) with time zone DEFAULT (now())
    );
CREATE INDEX "ix_purchase_order_invoice_item_create_time" ON "if_purchase_order_invoice_item" ("create_time" DESC);
COMMENT ON TABLE "if_purchase_order_invoice_item" IS '발주 Invoice Item 정보';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."id" IS '고유 식별자';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."invoice_no" IS 'Invoice 번호(SAP CINO)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."invoice_item_id" IS 'Invoice Item ID(SAP POSNR)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."description" IS '자재 설명(SAP BEZEI)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."manufacturer_code" IS '제조사 생산코드(SAP MATNR)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."material_id" IS '자재 ID';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."model_name" IS '자재 모델명(SAP MAKTX)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."sales_unit" IS '판매 단위(SAP VRKME)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."quantity" IS '발주 수량(SAP LFIMG)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."unit_price" IS '발주 단가(SAP NETPR)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."total_amount" IS '총 금액(SAP NETWR)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."currency" IS '통화 코드(SAP WAERK)';
COMMENT ON COLUMN "if_purchase_order_invoice_item"."create_time" IS 'SAP 조회 일시';
